### ISSUE TITLE
Feature Request: Allow associating the user with the client-side currentVisit

### ISSUE THREAD

**Issue by jrbj** [namolnad/ahoy-ios#2]
![Screen Shot 2021-01-27 at 8 21 20 AM](https://user-images.githubusercontent.com/49383/106081600-00ed1900-60ce-11eb-8061-faf8277445cc.png)

In the Rails version, there's an authenticate method that allows a user to be associated with a visit. After authenticating that user is automatically associated with that Visit and all subsequent events

Basically the issue is that in Event, we'd like to pass user_id to the top level of the method call, but we can only pass additional attributes into the properties dictionary (which is one level too deep for user_id to be used in the api)

**Comment by namolnad** [comment]
Thanks for the request and explanation @jrbj!

I've put together a [PR](#3) which I believe addresses your situation, but I'd like to make sure I understand it correctly. Are you looking to ensure user_id appears in each event payload as I've done in that PR or did I misunderstand your needs?

**Comment by namolnad** [comment]
Completed via #2
