### ISSUE TITLE
Is this Repo unmaintained?

### ISSUE THREAD

**Issue by hjhart** [namolnad/ahoy-ios#7]
Is this repository maintained any longer? I'm noticing a few unsupported issues an pull requests.

I suspect yes, it is. If so, what else are other folks using as a replacement?

**Comment by namolnad** [comment]
Turns out I had a period of time where my GitHub notifications were not set up correctly and I missed all of the activity/issues/questions on this repo. I believe these should be addressed now, so hopefully I can get all existing/future issues addressed

**Comment by hjhart** [comment]
Awesome, thanks @namolnad !
